services:
  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - 4040:4040
    command:
      - "http"
      - "atlantis:4141"
    env_file: "atlantis.env"
    depends_on:
      - atlantis
  atlantis:
    container_name: atlantis
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4141:4141
    user: "1000:atlantis"
    command: >
      atlantis
      server
      --atlantis-url=$ATLANTIS_URL
      --repo-config=$ATLANTIS_REPO_CONFIG
      --repo-allowlist=$REPO_ALLOWLIST
      --gh-user=$USERNAME
      --gh-token=$TOKEN
      --gh-webhook-secret=$SECRET
    volumes:
      - ../:/home/atlantis
    env_file:
      - ./atlantis.env