services:
  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - 4040:4040
    command:
      - "http"
      - "atlantis:4141"
    env_file:
      - ./atlantis.env
    depends_on:
      - atlantis
  # redis:
  #   image: redis:7.4-alpine@sha256:ee9e8748ace004102a267f7b8265dab2c618317df22507b89d16a8add7154273
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   command: redis-server --save 20 1 --loglevel warning --requirepass test123
  #   volumes:
  #     - redis:/data
  atlantis:
    # depends_on:
    #   - redis
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4141:4141
    command: >
      atlantis
      server
      --atlantis-url=$URL
      --repo-allowlist=$REPO_ALLOWLIST
      --gh-user=$USERNAME
      --gh-token=$TOKEN
      --gh-webhook-secret=$SECRET
    volumes:
      - .:/atlantis/src:ro
    env_file:
      - ./atlantis.env

# volumes:
#   redis:
#     driver: local